-- upgrade --
ALTER TABLE "reset" ALTER COLUMN timestamp TYPE TIMESTAMPTZ;
ALTER TABLE "nomination"
    ALTER COLUMN timestamp TYPE TIMESTAMPTZ,
    ALTER COLUMN score DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN last_updated TYPE TIMESTAMPTZ;
-- downgrade --
ALTER TABLE "reset" ALTER COLUMN timestamp TYPE TIMESTAMPTZ;
ALTER TABLE "nomination"
    ALTER COLUMN timestamp TYPE TIMESTAMPTZ,
    ALTER COLUMN score DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN last_updated TYPE TIMESTAMPTZ;
